import { useState, useEffect } from 'react';
import { storage, type IntakeAnswers } from '@/lib/storage';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { supabase } from '@/integrations/supabase/client';
import { Loader2 } from 'lucide-react';

const questions = [
  {
    key: 'children' as const,
    question: 'Do you have children living with you?',
    options: ['Yes', 'No', 'Yes but they are not with me'],
  },
  {
    key: 'finances' as const,
    question: 'Do you have independent access to money or a bank account?',
    options: ['Yes, fully', 'Limited access', 'No access'],
  },
  {
    key: 'documents' as const,
    question: 'Do you have access to your identification documents?',
    options: ['Yes', 'Some', 'No'],
  },
  {
    key: 'trustedPerson' as const,
    question: 'Do you have a trusted person outside the home you can contact safely?',
    options: ['Yes', 'Not sure', 'No'],
  },
  {
    key: 'timeline' as const,
    question: 'How soon are you thinking about leaving?',
    options: ['Within days', 'Within weeks', 'Not sure yet'],
  },
];

export function PlanTab() {
  const [answers, setAnswers] = useState<Partial<IntakeAnswers>>({});
  const [step, setStep] = useState(0);
  const [checklist, setChecklist] = useState<string | null>(storage.getSafetyChecklist());
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const existingAnswers = storage.getIntakeAnswers();
  const showIntake = !existingAnswers && !checklist;

  useEffect(() => {
    if (existingAnswers && !checklist) {
      generateChecklist(existingAnswers);
    }
  }, []);

  const handleAnswer = (key: string, value: string) => {
    const updated = { ...answers, [key]: value };
    setAnswers(updated);

    if (step < questions.length - 1) {
      setStep(step + 1);
    } else {
      const fullAnswers = updated as IntakeAnswers;
      storage.setIntakeAnswers(fullAnswers);
      generateChecklist(fullAnswers);
    }
  };

  const generateChecklist = async (intakeAnswers: IntakeAnswers) => {
    setLoading(true);
    setError(null);
    try {
      const { data, error: fnError } = await supabase.functions.invoke('safety-plan', {
        body: { answers: intakeAnswers },
      });

      if (fnError) throw fnError;
      const plan = data.plan || data.content || '';
      storage.setSafetyChecklist(plan);
      setChecklist(plan);
    } catch (e: any) {
      console.error('Failed to generate checklist:', e);
      setError('Unable to generate your safety plan right now. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleRetake = () => {
    storage.clearIntakeAnswers();
    setAnswers({});
    setStep(0);
    setChecklist(null);
  };

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center py-20 px-8">
        <Loader2 className="w-8 h-8 text-primary animate-spin mb-4" />
        <p className="text-muted-foreground text-center">Creating your personalized safety plan...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex flex-col items-center justify-center py-20 px-8 text-center">
        <p className="text-destructive mb-4">{error}</p>
        <Button onClick={() => { const a = storage.getIntakeAnswers(); if (a) generateChecklist(a); }} variant="outline">
          Try Again
        </Button>
      </div>
    );
  }

  if (checklist) {
    return (
      <div className="px-5 pt-6 pb-24">
        <h2 className="text-xl font-semibold text-foreground mb-6">Your Safety Plan</h2>
        <div className="bg-card rounded-2xl p-5 shadow-sm border border-border space-y-4">
          {checklist.split('\n').filter(Boolean).map((item, i) => (
            <p key={i} className="text-foreground leading-relaxed text-[15px]">{item}</p>
          ))}
        </div>
        <p className="text-xs text-muted-foreground mt-4 px-1 leading-relaxed">
          This plan was generated by AI based on your answers. It is a starting point — not legal advice. For personalized support, contact a local advocate.
        </p>
        <Button onClick={handleRetake} variant="outline" className="w-full mt-6">
          Retake Intake
        </Button>
      </div>
    );
  }

  if (showIntake) {
    const q = questions[step];
    return (
      <div className="px-5 pt-6 pb-24">
        <Progress value={((step + 1) / questions.length) * 100} className="mb-8 h-2" />
        <p className="text-sm text-muted-foreground mb-2">Question {step + 1} of {questions.length}</p>
        <h2 className="text-xl font-semibold text-foreground mb-8">{q.question}</h2>
        <div className="space-y-3">
          {q.options.map(option => (
            <button
              key={option}
              onClick={() => handleAnswer(q.key, option)}
              className="w-full text-left p-4 rounded-xl border-2 border-border bg-card text-foreground hover:border-primary transition-colors"
            >
              {option}
            </button>
          ))}
        </div>
      </div>
    );
  }

  return null;
}
