export const PRIVACY_POLICY_SECTIONS = [
  {
    title: "Safety Notice",
    content: "If you are concerned that someone may be monitoring your device, please read this policy on a safe device — such as a trusted friend's phone or a library computer. Accessing any website or document on a monitored device may be visible to the person monitoring it.",
    isWarning: true,
  },
  {
    title: "1. Introduction",
    content: `SafeStep is a mobile safety planning application designed to help survivors of domestic violence plan safely and access local resources. Your privacy and safety are the foundation of everything this app does.

This Privacy Policy explains what information SafeStep collects, how it is used, and what protections are in place. SafeStep is designed with a core privacy principle: your personal safety planning data never leaves your device. The app does not require an account, does not collect your name or contact information, and does not transmit any personally identifying information to any server.`,
  },
  {
    title: "2. Information We Do Not Collect",
    content: `SafeStep is intentionally designed to collect as little information as possible. We do not collect, store, or transmit any of the following:

• Your name, email address, phone number, or any contact information
• Your account credentials — SafeStep has no login and requires no account
• Your location data, except as described in Section 4
• Your intake questionnaire answers — stored only on your device
• Your AI-generated safety plan — stored only on your device
• Your chat history — stored only on your device
• Device identifiers, advertising IDs, or tracking cookies
• Any information about your identity, your abuser, or your situation

All data you enter into SafeStep is stored locally on your device and is never backed up to a cloud service, shared with third parties, or accessible by the SafeStep development team.`,
  },
  {
    title: "3. AI-Powered Features and the Anthropic Claude API",
    content: `SafeStep uses the Claude API, provided by Anthropic, PBC, to generate personalized safety planning checklists and power the in-app chat assistant. When you use these features, a limited amount of information is transmitted to Anthropic's servers to generate a response.

What is sent to Anthropic:
When you complete the intake questionnaire and request a safety plan, the following information is transmitted:
• Your answers to the five intake questions, in the form of a structured prompt
• No name, contact information, location, or device identifier is included

When you use the in-app chat, the following is transmitted:
• The text of your message
• A system-level instruction that defines how Claude should respond
• No personally identifying information is included unless you choose to type it yourself

Important: SafeStep's system prompt is designed to avoid asking for or encouraging users to share identifying information. However, if you voluntarily type your name, location, or other personal details into the chat, that text will be transmitted to Anthropic as part of your message. We recommend not including personally identifying information in your chat messages.

How Anthropic handles this data:
Anthropic processes your messages in order to generate a response. Anthropic's data handling practices are governed by their Privacy Policy (anthropic.com/legal/privacy). Key points:
• Anthropic does not sell your data to third parties
• API data is subject to Anthropic's data retention policy, which defaults to 30 days
• Anthropic may use API interactions to improve model safety under certain conditions

SafeStep has no control over Anthropic's data practices beyond what is described in their published policies.

AI Disclosure: In compliance with Anthropic's Usage Policy, SafeStep discloses that the safety planning checklist and in-app chat responses are generated by an artificial intelligence system. AI-generated content is clearly labeled within the app. AI-generated safety plans are a starting point and are not a substitute for guidance from a qualified domestic violence advocate or legal professional.`,
  },
  {
    title: "4. Location Data and the Google Places API",
    content: `SafeStep uses the Google Places API, provided by Google LLC, to display nearby domestic violence shelters, legal aid organizations, and counseling services on the Resources tab.

How location is used:
You may optionally grant SafeStep permission to access your device's location. If you grant this permission, your approximate location is used solely to pre-populate the ZIP code field on the Resources tab. Your precise GPS coordinates are not stored by SafeStep and are not transmitted to Google Places. Only the ZIP code you enter is used to query the Google Places API.

If you do not grant location permission, you may manually type any ZIP code. SafeStep functions fully without location permission.

What is sent to Google:
• The ZIP code you entered
• The search category (e.g., "domestic violence shelter")
• No name, device identifier, or account information is included

Google's handling of this data is governed by Google's Privacy Policy (policies.google.com/privacy).`,
  },
  {
    title: "5. On-Device Data Storage",
    content: `All data you generate within SafeStep — your intake answers, your safety plan, and your chat history — is stored exclusively on your device using local storage. This data is:

• Never transmitted to SafeStep's servers or any third-party server (except as described in Sections 3 and 4)
• Never included in any cloud backup unless your device's operating system is configured to back up app data
• Accessible only on your device
• Deleted permanently when you uninstall the app

If you are concerned that your device may be monitored or that someone may access your device physically, we recommend clearing your app data periodically or uninstalling SafeStep when not in use.`,
  },
  {
    title: "6. App Permissions",
    content: `SafeStep requests only the permissions necessary for its core functions:

• Location (optional): Used only to pre-populate the ZIP code field on the Resources tab. You can deny this and enter a ZIP code manually.
• Internet access (required): Required to make calls to the Anthropic Claude API and Google Places API.

SafeStep does not request access to your contacts, camera, microphone, photos, SMS messages, or any other sensitive device capability.`,
  },
  {
    title: "7. Children's Privacy",
    content: "SafeStep is intended for use by adults aged 18 and over. We do not knowingly collect any information from users under the age of 18.",
  },
  {
    title: "8. Third-Party Services",
    content: `SafeStep integrates with two third-party services, each with its own privacy policy:

• Anthropic, PBC (Claude API): anthropic.com/legal/privacy
• Google LLC (Google Places API): policies.google.com/privacy

SafeStep does not integrate with any advertising networks, analytics platforms, social media SDKs, or data brokers.`,
  },
  {
    title: "9. Security",
    content: `SafeStep is designed with the safety of domestic violence survivors as a primary consideration:

• All API communications use HTTPS encryption in transit
• No user accounts or passwords means there is no credential database that could be compromised
• Local-only storage means your data is not exposed through server breaches
• The decoy interface is designed to reduce the risk of detection by an abusive partner

Important limitation: HTTPS encryption protects your data in transit but does not protect against monitoring software (stalkerware) installed directly on your device. If you believe monitoring software may be installed on your phone, please use SafeStep on a different, trusted device.`,
  },
  {
    title: "10. Your Rights",
    content: `Because SafeStep does not collect personally identifying information and stores all data locally, you have full control over your data at all times:

• You can delete your safety plan and chat history at any time from within the app
• You can uninstall the app at any time, which permanently deletes all locally stored data
• You can use the app without granting location permission
• You can choose not to use the AI features, which avoids any data transmission to Anthropic

If you are located in the EEA, UK, or California, you may have additional rights under the GDPR, UK GDPR, or CCPA respectively. Because SafeStep does not collect personally identifying information, these rights are largely satisfied by design.`,
  },
  {
    title: "11. Changes to This Policy",
    content: "We may update this Privacy Policy from time to time. When we make material changes, we will update the effective date and, where feasible, provide notice within the app. Continued use of SafeStep after changes are posted constitutes your acceptance of the updated policy.",
  },
  {
    title: "12. Contact Us",
    content: `If you have questions about this Privacy Policy or SafeStep's data practices, please contact us.

If you are in immediate danger, please call 911. For support with domestic violence, contact the National Domestic Violence Hotline: 1-800-799-7233 or thehotline.org.`,
  },
];
